\
    name: Build NDS (devkitPro)
    on:
      push:
        branches: [ main ]
      workflow_dispatch:
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup devkitPro and build (docker)
          run: |
            docker run --rm -v "${{ github.workspace }}:/work" crossarm/devkitpro:latest /bin/bash -lc "cd /work && make || true"
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: flappy_ds_nds
            path: build/*.nds
